import React, {useContext, useEffect, useState} from 'react'
import styled from 'styled-components'

import {GlobalLoaderContext} from 'shared/providers/GlobalLoaderProvider'
import oktaService from 'web/services/oktaService'

const DivLookerContainer = styled.div`
  height: 100%;
  width: 100%;
  iframe {
    height: 100%;
    width: 100%;
  }
`

const API_URL = process.env.REACT_APP_API_HOST || 'http://localhost:4000'

/**
 * Renders Looker dashboards embedded in an iframe,
 * using a one-time URL generated by our API.
 * @category Pages
 * @namespace LookerContainer
 */
export default function LookerContainer() {
  const [embedUrl, setEmbedUrl] = useState(null)
  const {setIsLoading} = useContext(GlobalLoaderContext)

  useEffect(() => {
    async function getSsoUrl() {
      const bearerToken = oktaService.getBearerToken()
      const newEmbedUrlResponse = await fetch(
        API_URL + '/looker/sso_embed_url',
        {
          method: 'POST',
          headers: { authorization: bearerToken }
        }
      )
      const newEmbedUrlJSON = await newEmbedUrlResponse.json()
      setEmbedUrl(newEmbedUrlJSON.looker_url)
    }
    // clear loader from other pages
    setIsLoading(false)
    getSsoUrl()
  }, [setIsLoading])

  if (!embedUrl) return null
  return (
    <DivLookerContainer className='looker-container'>
      <iframe
        id='looker'
        title='looker'
        src={embedUrl}
      />
    </DivLookerContainer>
  )
}